#!/bin/sh

start() {
	# Blocker
	if [ -e /user/share/sn ]; then
		echo "Serial found..."
		if [ ! `head -1 sn` = `/usr/bin/getserial` ]; then
			echo "Wrong serial..."
			nohup omxplayer -b --loop /var/node/intro.mp4 --aspect-mode stretch >& /dev/null &
			while :; do sleep 2073600; done
		fi
	else
		echo "Writing serial..."
		/usr/bin/getserial > /user/share/sn
	fi
	echo "Passed serial check..."

	# Splash video
	nohup omxplayer -b /var/node/intro.mp4 --aspect-mode stretch >& /dev/null &
}

stop() {
	echo "OK"
}

restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
	;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
