#!/bin/sh

start() {
	# Startup scripts if needed
	nohup omxplayer -b /var/node/intro.mp4 --aspect-mode stretch &
}

stop() {
	echo "OK"
}

restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
	;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
