#! /bin/sh

case "$1" in
  start)
    /usr/bin/getserial > /var/node/build/sn
    /usr/bin/setwpasupplicant
    rm /etc/init.d/S02oneshot_scripts
    ;;
  stop)
    killall -q $NAME
    ;;
  *)
    echo "Usage: $0 {start|stop}" >&2
    exit 1
    ;;
esac

exit 0
