#!/bin/sh

start() {
	echo -n "Starting WPE: "
	/usr/bin/wpe --loop "http://localhost:8080" &> /dev/null &
}

stop() {
	echo -n "Stopping WPE: "
	killall wpe WPELauncher WPEWebProcess WPENetworkProcess &> /dev/null
	echo "OK"
}

restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
	;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
